import { Geist, Geist_Mono, Montserrat, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "scorecard/app/components/header";
import landingPageBg from 'scorecard/app/assets/landingPageBg.svg';
import Image from 'next/image';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
    weights: [400, 500, 600, 700, 800],
});

const plusJakartaSans = Plus_Jakarta_Sans({
    variable: "--font-plus-jakarta-sans",
    subsets: ["latin"],
   weights: [400, 500, 600, 700],
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${plusJakartaSans.variable} antialiased min-h-screen relative`}>
                <div className="absolute top-0 right-0 w-10/12 z-10 aspect-square">
                    <Image
                        src={landingPageBg}
                        fill
                        className='object-fill'
                        alt="Background decoration"
                        priority
                    />
                </div>
                <Header/>
                {children}
            </body>
        </html>
    );
}
